### ISSUE TITLE
boj 9012 괄호에 관련되어서 작성

### ISSUE THREAD

**Issue by choisaywhy** [CBNU-Nnet/ProblemSolving#10]
## BOJ 번호 Ex) 1981 - 후위표기식
BOJ 9012 - 괄호
## 사용언어 및 버전

1. 사용언어 
c

2. 언어버전

## 에러 결과
알 수 없음
Ex) 시간초과, 런타임 에러, 컴파일 에러

## 에러를 해결하기위해 참조했던 문서들
URL로 기술해주세요.
- 
- 
-

## 내가 생각하는 에러의 원인 
모르겠으면 모르겠다.

## 소스코드 첨부
#include<stdio.h>

int main()
{
	char arr[51] = {0,};
	int size = 0; // 크기
	int index = 0; // arr의 크기
	int n; // 반복횟수
	int i,j;

	scanf("%d", &n);
	
	for (i = 0; i < n; i++)
	{
		scanf("%s", arr);
		size = 0;
		for (j = 0; arr[j] != NULL; j++)
			size++;
		for (j = 0; j < size && index >= 0; j++)
		{
			if (arr[j] == '(')
				index++;
			else
				index--;
		}
		if (index == 0)
			printf("YES");
		else
			printf("NO");
		index = 0;
	}
	
	return 0;

}

```
Insert Code Here
```

**Comment by gun2841** [comment]
\n

**Comment by brewagebear** [comment]
해결된 질문이여서 닫습니다.
