### ISSUE TITLE
11004 - K번째 수

### ISSUE THREAD

**Issue by ckdgus0204** [CBNU-Nnet/ProblemSolving#12]
1. 사용언어 

 C++

2. 언어버전

C++14

3. 에러 결과

시간초과

## 에러를 해결하기위해 참조했던 문서들
- 퀵정렬(https://zetawiki.com/wiki/C%2B%2B_%ED%80%B5%EC%A0%95%EB%A0%AC_%EA%B5%AC%ED%98%84)
- 
-

## 내가 생각하는 에러의 원인 
시간초과를 더 줄여야 하는데 어떻게 더 줄일 수 있는지 모르겠습니다.
정렬방법을 라이브러리 함수 정렬도 써보고 해보았지만 안되네요.

## 소스코드 첨부
#include <iostream>
#include <algorithm>

using namespace std;

void quick_sort(long long a[], int L, int R) {
	int left, right, pivot = a[L];
	for (left = L, right = R; left<right; right--) {
		while (a[right] >= pivot && left<right) right--;
		if (left<right) a[left] = a[right];
		while (a[left] <= pivot && left<right) left++;
		if (left >= right) break;
		a[right] = a[left];
	}
	a[left] = pivot;
	if (left>L) quick_sort(a, L, left - 1);
	if (left<R) quick_sort(a, left + 1, R);
}
int main() {

	int k;
	int n;
	cin >>n;
	cin >>k;
	long long *arr = new long long[n];

	for (int i = 0; i < n; i++)
	{
		cin >> arr[i];
	}
	
	quick_sort(arr, 0, n-1);
	
	cout << arr[k - 1];
}

**Comment by gun2841** [comment]
N값은 최대 5000000 입니다.
https://algospot.com/forum/read/2496/
언어별 입출력속도 비교입니다.

**Comment by gun2841** [comment]
Worst-case를 생각하면
퀵정렬은 대부분 빠르긴 하지만
이 문제에서 이미 정렬된 배열을 가지고 할 경우 더 느릴수있습니다.

**Comment by gun2841** [comment]
라이브러리 정렬함수와 scanf사용하거나
	ios_base::sync_with_stdio(false) 이용하여 cin , cout 속도를 높이는 방법도 있습니다

-------------------------------
qsort + scanf 사용 => 1952ms
sort + scanf 사용 => 1540ms
-------------------------------
이외에 
https://neurowhai.tistory.com/274   있습니다

**Comment by brewagebear** [comment]
완료된 질문이므로 이슈 Close하겠습니다.
