### ISSUE TITLE
무슨에러인지 모르겠는 에러에 관련되어서 작성

### ISSUE THREAD

**Issue by choisaywhy** [CBNU-Nnet/ProblemSolving#9]
## BOJ 번호 Ex) 1981 - 후위표기식
10828 - 스택
## 사용언어 및 버전

C

## 에러 결과
visual studio에서는 실행되나 제출하면 틀렸다함

## 내가 생각하는 에러의 원인 
능력부족..

## 소스코드 첨부

#include<stdio.h>
#include<string.h>
int arr[100]; // 스택
int index = -1; // 인덱스 조절을 위함
int push();
int pop();
int size();
int empty();
int top();

int main()
{
	int n;
	char fun[6] = {0,}; // 함수를 실행하기 위함
	scanf("%d",&n);

	while (n > 0)
	{
		getchar();
		scanf("%s", fun);
		
		if (strcmp(fun, "push") == 0)
			push();
		else if (strcmp(fun, "pop") == 0)
			pop();
		else if (strcmp(fun, "size") == 0)
			size();
		else if (strcmp(fun, "empty") == 0)
			empty();
		else if (strcmp(fun, "top") == 0)
			top();
		else
			printf("바부바부");
		n--; // 실행횟수 세기
	}

	return 0;

}

int push() // 스택에 정수 넣기
{
	int num;
	
	index++; // 첨에 -1이던 인덱스를 +1해주고

	scanf("%d", &num); // 정수를 입력받음
	arr[index] = num; // 스택에 넣기
	
	return 0;

}
int pop() // 출력과 삭제
{
	if (index >= 0) // 스택에 정수가 있으면 == 인덱스가 -1이 보다 크면
	{
		printf("%d", arr[index]); // 출력
		arr[index] = NULL; // 삭제
		index--; // 인덱스 하나 지우기
	}
	else // 정수 없으면
		printf("%d",index); // -1출력 
	return 0;
}
int size() // 정수개수
{
	printf("%d", index+1);
	return 0;
}
int empty() // 비었나
{
	if (index >= 0) // 안빔
		printf("0");
	else // 빔
		printf("1");
	return 0;

// index >= 0 ? 0:1

// 참 거짓으로도 해보기
}
int top()
{
	if (index >= 0)
		printf("%d", arr[index]);
	else
		printf("-1");
	return 0;
}

**Comment by gun2841** [comment]
\n 입니다.
출력이 한줄에 하나 씩이여서 
printf에 \n 넣어주세요

**Comment by brewagebear** [comment]
해결된 질문이여서 닫습니다.
